### ISSUE TITLE
Enable radiotools for python 3

### ISSUE THREAD

**Issue by fschlueter** [cg-laser/radiotools#3]
Hi,
this might be a good place to share opinions about the conversion to a python 2 and 3 compatible library?!
I started a corresponding branch! Please share any opinion.

**Comment by anelles** [comment]
I think as @christophwelling has already found when testing for NuRadioMC, the Py3 transition needs some changes. 
@fschlueter we are planning to move NuRadioMC and NuRadioReco to py3 as default soon. So this issue may take priority now.

**Comment by christophwelling** [comment]
Yes, that branch is outdated. Most of the necessary changes are already implemented.
